name: escritura
description: 'An app for building strong daily habits in interacting with the Word of God.'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^7.2.0
  permission_handler: ^12.0.1
  whisper_ggml: ^1.5.0
  record: ^5.0.4
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

