name: escritura
description: 'An app for building strong daily habits in interacting with the Word of God.'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.3.0+8

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  bible_parser_flutter: ^0.1.0
  word_tools:
    git:
      url: https://github.com/el-apps/word_tools.git
      ref: v0.1.1
  provider: ^6.1.5
  freezed_annotation: ^3.1.0
  flutter_launcher_icons: ^0.14.4
  share_plus: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/kjv.xml

